mySite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wtv',include('polls.urls')),
    url(r'^cook',include('testApp.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^/(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(),name='results'),
    url(r'^/(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

]

testApp/urls.py
from django.conf.urls import url
from . import views
app_name = 'testApp'
urlpatterns = [
	
	url(r'^/$',views.IndexView,name='default'),
	
	url(r'/(?P<pk>[\w-]*)/*',views.MealsList,name='wtvman'),
	
]

polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length = 150)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text


	

testApp/models.py
from __future__ import unicode_literals
from django.db import models
# Create your models here.
class Meal(models.Model):		
	flavor = models.CharField(max_length=120)
	name = models.CharField(max_length=300,primary_key=True)
	rating = models.IntegerField(default=1)
	def __str__(self):
		return self.name
	def getPrice(self):
		price = 0
		for i in self.ingredient_set.all():
			price += i.price
		return price
	def getName(self):
		return ' '.join(self.name.split('-'))

class Ingredient(models.Model):
	name = models.CharField(max_length=200) 
	price = models.IntegerField(default=0)
	meal = models.ForeignKey(Meal,on_delete=models.CASCADE)
	
	def __str__(self):
		return self.name + ' costs '+ str(self.price) +' dollars'
	def pricePlus(self):
		self.price += 1 
	def priceMinus(self):
		if(self.price>=1):
			self.price -=1
		else:
			self.price = 0 
	

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Question,Choice
from django.views import generic

def checkId(question_id):
	try:
		q = Question.objects.get(pk=question_id)
		return q
	except Question.DoesNotExist:
		raise Http404("The question you're looking for doesn't seem to exist")
# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

testApp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Meal,Ingredient
from django.http import HttpResponse
# Create your views here.
def MealsList(request,pk):
	all = True
	if(request.POST.get('priceUp')):
		ing = Ingredient.objects.get(pk=request.POST['priceUp'])
		ing.pricePlus()
		ing.save()

	if(request.POST.get('priceDown')):
		ing = Ingredient.objects.get(pk=request.POST['priceDown'])
		ing.priceMinus()
		ing.save()
	
	if(request.POST.get('adding')):
		i1 = Ingredient()
		i1.name = request.POST['adding']
		i1.meal = Meal.objects.get(pk=pk)
		i1.save()
	if(request.POST.get('ff')):
		all = False
	if(request.POST.get('sf')):
		all = True
	
	context = {
	'meal' : Meal.objects.get(pk=pk),
	'all':all
	}
	print str(all)
	template_name = 'testApp/ingredients.html'
	return render(request,template_name,context)
def DefaultView(request):
	return HttpResponse('default view it is')
def IndexView(request):
	template_name='testApp/defaultMealsList.html'
	context = {'meals':Meal.objects.all()}
	return render(request,template_name,context)

polls/templates/polls/detail.html
<body style='background-color:black;text-align:center;font-size:25px;color:white;'>

	<h1>{{ question.question_text }}</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form action = "{% url 'polls:vote' question.id %}" method="post">
		{%csrf_token%}

{% for choice in question.choice_set.all %}
	<input type='radio' name='choice' id='choice{{forloop.counter}}' value='{{choice.id}}'/>
    <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br/>
{% endfor %}
<input type='submit' value='Vote'/>
	</body>

polls/templates/polls/index.html
<body style='background-color:black;text-align:center;font-size:25px;color:white;'>
{% if latest_question_list %}

	<br/>
    <div style='text-align:center;'>
    {% for question in latest_question_list %}
        <p><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></p><br/>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

polls/templates/polls/results.html
<body style='background-color:black;text-align:center;font-size:25px;color:white;'>

<h1>{{ question.question_text }}</h1>

{%for choice in question.choice_set.all%}
<p>{{choice.choice_text}} -- {{choice.votes}} votes</p>
{%endfor%}
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>

testApp/templates/testApp/defaultMealsList.html
<style>
body{
	background-color:black;
	color:white;
	text-align:center;
}

</style>
<body>
<h1> Choose which meal you want to cook</h1>
{%if meals%}
{%for m in meals%}
<h1> <a href='{{m.name}}'>{{m.getName}}</a></h1>
{%endfor%}
{%else%}
<h1>No meals available at the moment, sorry.</h1>
{%endif%}
</body>

testApp/templates/testApp/ingredients.html
<head>
</head>
<body style='
background-color:black;
color:white;
text-align:center;'
	  id='body'
	  >
<div id='main'>
{%if meal %}
<h1> {{meal.getName}} is usually made of:</h1>
{%for ing in meal.ingredient_set.all%}
	{%if ing.price != 0 or all%}
<h2>{{ing.name}} -- {{ing.price}} dollars</h2>
<form action="#" method="post">
	{% csrf_token %}
 <button type="submit" class="btn" value="{{ing.id}}" name="priceUp" id='{{ing.name}}'>+</button>

 <button type="submit" class="btn" value="{{ing.id}}" name="priceDown" id='{{ing.name}}'>-</button>
</form>
	{%endif%}
{%endfor%}
<h2>Therefore the total cost of {{meal.getName}} is {{meal.getPrice}} dollars</h2>
	<form action='#' method ='post'>
		{%csrf_token%}
		<button id='filterFree' name='ff' value = {{all}}>Hide free ingredients</button>
		<button id='filterFree' name='sf' value = {{all}}>Show free ingredients</button>
	</form>
	<button id='newOne' >Add new Ingredient</button>
{%else%}
<h1>whaddup</h1>
	{%endif%}
	</div>
<h2 id='footer'><a href='/cook/'>Go back to main screen</a></h2>
	<script>
		added = false;
	function addForm(){
		if(!added){
		str = '<br/><input type=\'text\' id="enterHere"/>'
			+'<form action="#" method="post">'
			+"{% csrf_token %}"
			+'<button id="addBtn" name="adding" value="">Add</button><br/>'
			+'</form>';
		var div = document.createElement('div');
		div.innerHTML = str;
	document.getElementById('main').appendChild(div);
	document.getElementById('addBtn').addEventListener('click',submitNew);
		added = true;}
	}
	window.onload = document.getElementById('newOne').addEventListener('click',addForm);
	
		function submitNew(){
		iName = document.getElementById("enterHere").value;
		document.getElementById('addBtn').value = iName;
		console.log(iName+ document.getElementById('addBtn').value);
		}
		
		
	</script>
</body>